### ISSUE TITLE
As a designer I want to create an item list which can be seen in game

### ISSUE THREAD

**Issue by TomWenman19** [UoSGamesGroups/first-semester-l4-5-group-11#24]
Create a list which will be shown in game that players know what to search for. 
Cigarettes
Purple sweater
Set of keys
Lighter
Medicine bottle
Phone
Hairbrush
Lipstick
2hrs.

**Comment by J-Marks** [comment]
List of about 10 items for each room that could be placed each room of the house. 1 hour 50 mins.
